export enum RevupCommand {
  CALL_METHOD = 'call-method',
  CALL_FUNCTION = 'call-function',
  EPOCH = 'epoch',
  EXPORT_ABI = 'export-abi',
  NEW_ACCOUNT = 'new-account',
  NEW_COMPONENT = 'new-component',
  RESET = 'reset',
  PUBLISH = 'publish',
  SET_ACCOUNT = 'set-default-account',
  SHOW = 'show',
  SHOW_CONFIGS = 'show-configs',
  SHOW_LEDGER = 'show-ledger',
  TRANSFER = 'transfer',
}
